name: Check build

on:
  push:
    branches:
      - 'ci-**'
    paths:
      - 'srcpkgs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Build changed packages.
  build:
    name: Build packages
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/void-linux/void-${{ matrix.config.libc }}-full
      options: --platform ${{ matrix.config.platform }} --privileged
      volumes:
        - /dev:/dev
      env:
        ARCH: '${{ matrix.config.arch }}'
        BOOTSTRAP: '${{ matrix.config.host }}'
        TEST: '${{ matrix.config.test }}'

    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: x86_64,       host: x86_64,      libc: glibc, platform: linux/amd64, test: 1 }
          - { arch: aarch64,      host: x86_64,      libc: glibc, platform: linux/amd64, test: 0 }
          - { arch: x86_64-musl,  host: x86_64-musl, libc: musl,  platform: linux/amd64, test: 1 }
          - { arch: aarch64-musl, host: x86_64-musl, libc: musl,  platform: linux/amd64, test: 0 }

    steps:
      - name: Prepare container
        run: |
          # switch to repo-ci mirror
          mkdir -p /etc/xbps.d && cp /usr/share/xbps.d/*-repository-*.conf /etc/xbps.d/
          sed -i 's|repo-default|repo-ci|g' /etc/xbps.d/*-repository-*.conf
          # install dependencies
          xbps-install -Syu xbps && xbps-install -yu && xbps-install -y sudo bash curl git
          # create non-root user
          useradd -G xbuilder -M builder

      - name: Clone and checkout
        uses: classabbyamp/treeless-checkout-action@v1

      - name: Configure ethereal mode
        working-directory: void-packages
        run: |
          cat <<EOF > etc/conf
          XBPS_ALLOW_CHROOT_BREAKOUT=yes
          XBPS_CHROOT_CMD=ethereal
          XBPS_MIRROR=https://repo-fastly.voidlinux.org/current
          EOF
          ln -s / masterdir

      - name: Find changed templates
        run: sudo -Eu builder common/travis/changed_templates.sh

      - name: Build and check packages
        run: sudo -Eu builder common/travis/build.sh "$BOOTSTRAP" "$ARCH" "$TEST"

      - name: Show files
        run: sudo -Eu builder common/travis/show_files.sh "$BOOTSTRAP" "$ARCH"

      - name: Compare to previous
        run: sudo -Eu builder common/travis/xpkgdiff.sh "$BOOTSTRAP" "$ARCH"

      - name: Check file conflicts
        if: matrix.config.arch == 'x86_64' # the arch indexed in xlocate
        run: |
          if [ -s /tmp/templates ]; then
              export XDG_CACHE_HOME="$PWD/.cache"
              sudo -Eu builder xlocate -S &&
              sudo -Eu builder common/scripts/lint-conflicts
          fi

      - name: Verify repository state
        run: |
          mkdir -p /check-install &&
          chown builder:builder /check-install &&
          sudo -Eu builder common/travis/check-install.sh "$BOOTSTRAP" "$ARCH"