name: Build packages

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to build'
        required: true
        default: ''
      x86_64:
        description: 'Architecture x86_64'
        required: true
        type: choice
        options:
            - 'yes'
            - 'no'
      aarch64:
        description: 'Architecture aarch64'
        required: true
        type: choice
        options:
            - 'yes'
            - 'no'
      test:
        description: 'Run tests'
        required: true
        type: choice
        options:
            - 'yes'
            - 'no'
      restricted:
        description: 'Allow restricted packages'
        required: true
        type: choice
        options:
            - 'yes'
            - 'no'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Select architectures
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.architectures.outputs.architectures }}
    steps:
      - name: Checkout repository
        uses: classabbyamp/treeless-checkout-action@v1

      - name: Select architectures
        id: architectures
        env:
          X86_64: ${{ inputs.x86_64 || 'yes' }}
          AARCH64: ${{ inputs.aarch64 || 'yes' }}
        run: |
          architectures=$(sh ./.github/scripts/arch_type.sh "$X86_64" "$AARCH64")
          echo "architectures=$architectures" >> "$GITHUB_OUTPUT"

  build:
    needs: prepare
    name: Build ${{ inputs.package || 'glsl_analyzer' }} (${{ matrix.arch }})
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/void-linux/void-glibc-full
      options: --platform linux/amd64 --privileged
      volumes:
        - /dev:/dev
      env:
        ARCH: '${{ matrix.arch }}'
        BOOTSTRAP: x86_64
        TEST: "${{ inputs.test == 'yes' && 1 || 0 }}"
        XBPS_ALLOW_RESTRICTED: "${{ inputs.restricted == 'yes' && 1 || 0 }}"

    strategy:
      fail-fast: false
      matrix:
        arch: ${{ fromJSON(needs.prepare.outputs.architectures) }}

    steps:
      - name: Prepare container
        run: |
          # switch to repo-ci mirror
          mkdir -p /etc/xbps.d && cp /usr/share/xbps.d/*-repository-*.conf /etc/xbps.d/
          sed -i 's|repo-default|repo-ci|g' /etc/xbps.d/*-repository-*.conf
          # install dependencies
          xbps-install -Syu xbps && xbps-install -yu && xbps-install -y base-devel nodejs-lts sudo bash curl git file
          # create non-root user
          useradd -G xbuilder -M builder

      - name: Clone and checkout
        uses: classabbyamp/treeless-checkout-action@v1

      - name: Clone void-packages
        run: git clone --depth=1 https://github.com/void-linux/void-packages.git void-packages

      - name: Configure ethereal mode
        working-directory: void-packages
        run: |
          cat <<EOF > etc/conf
          $(if [ "${{ inputs.restricted }}" = "yes" ]; then echo XBPS_ALLOW_RESTRICTED=yes; fi)
          XBPS_ALLOW_CHROOT_BREAKOUT=yes
          XBPS_CHROOT_CMD=ethereal
          XBPS_MIRROR=https://repo-fastly.voidlinux.org/current
          EOF
          ln -s / masterdir

      - name: Merge template
        env:
          PACKAGE: ${{ inputs.package || 'glsl_analyzer' }}
        run: |
          rm -fr "void-packages/srcpkgs/$PACKAGE"
          cp -fr "srcpkgs/$PACKAGE" "void-packages/srcpkgs/"

      - name: Prepare xbps-src
        working-directory: void-packages
        run: /bin/bash ./xbps-src binary-bootstrap

      - name: Build package
        working-directory: void-packages
        env:
          PACKAGE: ${{ inputs.package || 'glsl_analyzer' }}
        run: |
          /bin/bash ./xbps-src -j$(nproc) pkg "$PACKAGE"

      - name: Sign and index
        working-directory: void-packages/hostdir/binpkgs
        env:
          PRIV_KEY: ${{ secrets.PRIV_KEY }}
        run: |
          repo_dir="."
          if [ "${{ inputs.restricted }}" = "yes" ]; then
            repo_dir="nonfree"
          fi
          cd "$repo_dir"
          echo "$PRIV_KEY" > private.pem
          xbps-rindex -a *.xbps
          xbps-rindex -s --signedby "VoizLinux <iz@anrix.org>" --privkey private.pem "$PWD"
          xbps-rindex -S --privkey private.pem *.xbps
          rm private.pem

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.package || 'glsl_analyzer' }}-${{ matrix.arch }}
          path: void-packages/hostdir/binpkgs/*
          retention-days: 7